const INFOCLIENT = [
  {
    label: 'Nombre',
    placeholder: 'Nombre aquí',
    customClass: '',
    required: true,
    disabled: true,
    type: 'text',
  },
  {
    label: 'Apellido',
    placeholder: 'Apellido aquí',
    customClass: '',
    required: true,
    disabled: false,
    type: 'text',
  },
  {
    label: 'E-mail',
    placeholder: 'E-mail aquí',
    customClass: '',
    required: true,
    disabled: false,
    type: 'email',
  },
  {
    label: 'Teléfono',
    placeholder: 'Teléfono aquí',
    customClass: '',
    required: false,
    disabled: false,
    type: 'text',
  },
  {
    label: 'Dirección',
    placeholder: 'Calle, Número, Colonia, Municipio, Estado, CP',
    customClass: '',
    required: false,
    disabled: false,
    type: 'text',
  },
  {
    label: 'Input número 1',
    placeholder: '0.00',
    customClass: '',
    required: true,
    disabled: false,
    type: 'number',
  },
  {
    label: 'Input número 2',
    placeholder: '0.00',
    customClass: '',
    required: true,
    disabled: false,
    type: 'number',
  },
  {
    label: 'Entidad',
    placeholder: '0.00',
    customClass: '',
    required: true,
    disabled: false,
    type: 'select',
    options: [
      'Seleccione una entidad', 'Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas', 'Chihuahua', 'Coahuila', 'Colima', 'CDMX', 'Durango', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Jalisco', 'Estado de México', 'Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas',
    ],
  },
];

export default INFOCLIENT;
